name: "CouchDB in GitHub Actions (2023)"
description: "Start a CouchDB server (on port 5984)"

branding:
  icon: database
  color: red

inputs:
  couchdb-version:
    description: CouchDB version to use (default "3.3.2")
    required: false
    default: 3.3.2

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.couchdb-version }}
